config/routes.rb
Rails.application.routes.draw do
  require "que/web"
  mount Que::Web => "/que"

  root 'demos#new'
  resources :demos, param: :token, path: '/'

end

app/models/demo.rb
class Demo < ActiveRecord::Base
	TOKEN_LENGTH = 32

	attr_accessor :email

	belongs_to :template
	belongs_to :requestor

	enum status: [:pending, :confirmed, :provisioning, :provisioned, :error]

	validates :template_id, presence: true
	validates :requestor_id, presence: true
	validates :email, presence: true

	before_validation :set_requestor
	before_create :set_token, :set_expirations, :set_pending

	composed_of :provisioning_status, allow_nil: true, mapping: %w(provisioning_status_name status_name)

	def to_param
		self.token
	end

	def url
		Rails.application.routes.url_helpers.demo_url(self)
	end

	def display_description
		self.description.present? ? self.description : self.template.name
	end

	def provision_later
		ProvisionDemoJob.perform_later(self)
	end

	def error!(provisioning_error)
		update(status: :error, provisioning_error: provisioning_error)
		deprovision!
	end

	def provisioning!
		update(status: :provisioning, provisioning_status_name: :creating)
	end

	def provisioned!
		update(status: :provisioned, provisioning_status_name: :complete)
	end

	def provision!
		return unless confirmed? && self.skytap_id.blank?

		provisioning!

		config = SkytapAPI.post('configurations', template_id: template.skytap_id)

		update(skytap_id: config.id)

		raise 'The requested template does not have a published URL configured' if 
			config.publish_sets.length == 0 || !config.publish_sets.first.desktops_url

		update(published_url: config.publish_sets.first.desktops_url)

		update(provisioning_status_name: :adding)

		SkytapAPI.post("projects/#{ENV['demo_environments_project_id']}/configurations/#{config.id}") if ENV['demo_environments_project_id']

    update(provisioning_status_name: :assigning)

		SkytapAPI.put(config.url,
			owner: requestor.find_or_create_skytap_url
		)

		update(provisioning_status_name: :scheduling)

    SkytapAPI.post("schedules",
      title: "Schedule for #{config.name} - [#{config.id}]",
      configuration_id: config.id,
      start_at: Time.now.utc,
      end_at: usage_expiration,
      delete_at_end: true,
      time_zone: "UTC"
    )

    update(provisioning_status_name: :connecting)

    # TODO - limited to a single region
    SkytapAPI.post("tunnels?source_network_id=#{config.networks.first.id}&target_network_id=#{ENV['global_network_id']}") if ENV['global_network_id']

    update(provisioning_status_name: :starting)

		SkytapAPI.put(config.url,
			name: name,
			runstate: "running"
		)

		provisioned!
	end

	def provisionable?
		confirmed? && !expired?
	end

	def ready?
		provisioned? && !expired?
	end

	def expired?
		self.confirmation_expiration <= Time.now || self.usage_expiration <= Time.now
	end

	private

	def name
		"Demo Environment - #{template.name} - #{requestor.email} #{description.present? ? ' - ' + description : ''}"
	end

	def set_requestor
		if self.email && !self.requestor
			self.requestor = Requestor.where(email: email).first_or_create
			self.requestor.errors[:email].each { |error| self.errors.add(:email, error) }
		elsif !self.email && self.requestor
			self.email = self.requestor.email
		end
	end

	def set_token
		self.token = SecureRandom.hex(TOKEN_LENGTH) unless self.token
	end

	def set_expirations
		self.confirmation_expiration = Time.now.utc + ENV['confirmation_period_hours'].to_i.hours unless self.confirmation_expiration
		self.usage_expiration = Time.now.utc + ENV['usage_period_hours'].to_i.hours unless self.usage_expiration
	end

	def set_pending
		self.status = :pending
	end

	def deprovision!
		SkytapAPI.delete("configurations/#{self.skytap_id}") if self.skytap_id
	end
end

app/models/provisioning_status.rb
class ProvisioningStatus
  include ActiveModel::Serializers::JSON

  attr_accessor :status_name, :percent_complete, :message

  STATUS_MAP = {
    creating: { percent_complete: 0, message: "Provisioning environment" },
    adding: { percent_complete: 25, message: "Adding environment to project" },
    assigning: { percent_complete: 40, message: "Assigning environment ownership" },
    scheduling: { percent_complete: 55, message: "Configuring access window" },
    connecting: {percent_complete: 70, message: "Connecting to global network" },
    starting: { percent_complete: 85, message: "Starting environment" },
    complete: { percent_complete: 100, message: "Provisioning complete" }
  }.with_indifferent_access

  def initialize(status_name)
    raise ArgumentError unless STATUS_MAP.key?(status_name)
    
    @status_name = status_name
    @percent_complete = STATUS_MAP[status_name][:percent_complete]
    @message = STATUS_MAP[status_name][:message]
  end

  def attributes
    {'status_name' => nil, 'percent_complete' => nil, 'message' => nil}
  end
end

app/models/requestor.rb
require 'skytap_api'

class Requestor < ActiveRecord::Base
	has_many :demos
	validates :email, presence: true, uniqueness: true, whitelisted_email: true

  def find_or_create_skytap_url
    self.skytap_url ||= create_skytap_user
  end

  private

  def create_skytap_user
    user_obj = SkytapAPI.post("users",
      login_name: login_name,
      first_name: first_name,
      last_name: last_name,
      password: SecureRandom.hex,
      email: ENV['shadow_users_email']
    )

    update(skytap_url: user_obj.url)

    SkytapAPI.post("departments/#{ENV['shadow_users_dept_id']}/users/#{user_obj.id}") if ENV['shadow_users_dept_id']
    
    { "cumulative_svms" => ENV['shadow_user_svm_hours_monthly_quota'],
      "concurrent_storage_size" => ENV['shadow_users_storage_quota_mb'],
      "concurrent_svms" => ENV['shadow_user_concurrent_svms_quota']
    }.each do |quota_name, quota_value|
      SkytapAPI.post("users/#{user_obj.id}/quotas",
        name: quota_name,
        limit: quota_value
      ) if quota_value
    end 

    self.skytap_url
  end

  def neutralized_email
    self.email.gsub(/[@\.]/, "-")
  end

  def login_name
    "#{neutralized_email}@#{ENV['shadow_user_domain']}"
    neutralized_email
  end

  def first_name
    neutralized_email
  end

  def last_name
    "shadow-user"
  end	
end

app/models/template.rb
require 'skytap_api'

class Template < ActiveRecord::Base
	has_many :demos
	validates :skytap_id, presence: true
	validates :name, presence: true
	validates :region_name, presence: true

	def self.pull
		current_template_skytap_ids = Template.pluck(:skytap_id)

		new_template_info = SkytapAPI.get("projects/#{ENV['templates_project_id']}/templates")
		new_template_skytap_ids = new_template_info.map {|template_info| template_info.id.to_i}

		current_template_skytap_ids.each do |template_skytap_id|
			unless new_template_skytap_ids.include?(template_skytap_id)
				Template.find_by(skytap_id: template_skytap_id).destroy
			end
		end

		new_template_info.each do |template_info|
			Template.create(skytap_id: template_info.id, name: template_info.name, region_name: template_info.region) unless current_template_skytap_ids.include?(template_info.id.to_i)
		end

		all
	end

	def self.pull_later
		PullTemplatesJob.perform_later
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
end

app/controllers/demos_controller.rb
class DemosController < ApplicationController
  def new
    @demo = Demo.new
  end

  def create
    @demo = Demo.new(demo_params)
    if @demo.save
      DemoConfirmationMailer.confirmation_email(@demo).deliver_later(queue: ApplicationJob::DEFAULT_QUEUE)
      respond_to do |format|
        format.html {
          redirect_to root_path, notice: 'OK, check your email.'          
        }
        format.json {
          render json: @demo, status: :created
        }
      end
    else
      respond_to do |format|
        format.html {
          flash[:alert] = "Please correct the errors below."
          render 'new'
        }
        format.json {
          render json: @demo.errors.full_messages, status: :bad_request
        }
      end
    end
  end

  def show
    @demo = Demo.find_by!(token: params[:token]) 

    @demo.confirmed! if @demo.pending?

    @description = @demo.display_description

    if @demo.ready? #fulfilled and not expired
      @url = @demo.published_url
    elsif @demo.provisionable?
      @demo.provision_later
    elsif @demo.error?
      @error = @demo.provisioning_error
    end

    respond_to do |format|
      format.html
      format.json {
        render json: @demo, status: (@demo.error? || @demo.expired? ? :bad_request : :ok)
      }
    end
  end

  private

  def demo_params
    params.require(:demo).permit(:email, :template_id, :description)
  end
end

app/views/demos/new.html.erb
<% flash.each do |key, value| %>
  <%= content_tag :div, value, class: "flash #{key}" %>
<% end %>

<p class='instructions'>Enter the details for your demo request:</p>

<%= simple_form_for @demo do |f| %>
	<%= f.association :template %>
	<%= f.input :email %>
	<%= f.input :description %>
  <button type="submit" class="big_button">Create Demo</button>
<% end %>

app/views/demos/show.html.erb
<div class='description'><%= @description %></div>

<div class='instructions'>
  <span data-status="confirmed" style="<%= @demo.confirmed? ? '' : 'display:none;'%>">Please wait while provisioning starts.</span>    
  <span data-status="provisioning" style="<%= @demo.provisioning? ? '' : 'display:none;'%>">Please wait while your demo is provisioned.</span>
  <span data-status="ready" style="<%= @demo.ready? ? '' : 'display:none;'%>">Your demo is available for use.</span>
  <span data-status="expired" style="<%= @demo.expired? ? '' : 'display:none;'%>">Your demo has expired. You can <%= link_to 'request a new demo', new_demo_path %>.</span>
  <span data-status="error" style="<%= @demo.error? ? '' : 'display:none;'%>">An error has occurred. Please contact your administrator or <%= link_to 'request a new demo', new_demo_path %>.
  <span data-status="error" id="error_text"><%= @error %></span>
</div>

<a data-status="ready" class="big_button" id="demo_button" href="<%= @demo.published_url %>" style="<%= @demo.ready? ? '' : 'display:none;'%>">Access Demo</a>

<span id="provisioning_progressbar_section">
  <progress data-status="provisioning" id="provisioning_progressbar" max="100" value="0" style="<%= @demo.provisioning? ? '' : 'display:none;'%>"></progress>

  <span data-status="provisioning" id="provisioning_percent_complete" style="<%= @demo.provisioning? ? '' : 'display:none;'%>"><%= @demo.provisioning_status.try(:percent_complete) %></span>
</span>

<span data-status="provisioning" id="provisioning_status" style="<%= @demo.provisioning? ? '' : 'display:none;'%>"><%= @demo.provisioning_status.try(:message) %></span>

<% if @demo.confirmed? || @demo.provisioning? %>
  <script>$(document).ready(maintainStatus);</script>
  <noscript>Please refresh the page for updates.</noscript>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Demo Creator</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <script>POLL_INTERVAL_MS = <%= ENV['poll_interval_ms'] %>;</script>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <h1 class='logo'><%= link_to 'Demo Creator', root_path %></h1>
    <%= yield %>
  </div>
</body>
</html>